CREATE OR REPLACE VIEW CLASIFICACION AS
SELECT
    E.NOMBRE,
    SUM(CASE WHEN P.ID_EQUIPO_LOCAL = E.ID_EQUIPO AND P.GOLES_LOCAL > P.GOLES_VISITANTE THEN 1
             WHEN P.ID_EQUIPO_VISITANTE = E.ID_EQUIPO AND P.GOLES_VISITANTE > P.GOLES_LOCAL THEN 1
             ELSE 0
        END) AS VICTORIAS,
    SUM(CASE WHEN P.ID_EQUIPO_LOCAL = E.ID_EQUIPO AND P.GOLES_LOCAL < P.GOLES_VISITANTE THEN 1
             WHEN P.ID_EQUIPO_VISITANTE = E.ID_EQUIPO AND P.GOLES_VISITANTE < P.GOLES_LOCAL THEN 1
             ELSE 0
        END) AS DERROTAS,
    SUM(CASE WHEN P.ID_EQUIPO_LOCAL = E.ID_EQUIPO THEN P.GOLES_LOCAL ELSE P.GOLES_VISITANTE END) AS GOLES_A_FAVOR,
    SUM(CASE WHEN P.ID_EQUIPO_LOCAL = E.ID_EQUIPO THEN P.GOLES_VISITANTE ELSE P.GOLES_LOCAL END) AS GOLES_EN_CONTRA,
    SUM(CASE WHEN P.ID_EQUIPO_LOCAL = E.ID_EQUIPO THEN P.GOLES_LOCAL ELSE P.GOLES_VISITANTE END) - 
    SUM(CASE WHEN P.ID_EQUIPO_LOCAL = E.ID_EQUIPO THEN P.GOLES_VISITANTE ELSE P.GOLES_LOCAL END) AS DIFERENCIA_GOLES
FROM
    EQUIPOS E
    LEFT JOIN PARTIDOS P ON E.ID_EQUIPO = P.ID_EQUIPO_LOCAL OR E.ID_EQUIPO = P.ID_EQUIPO_VISITANTE
WHERE
    P.ID_JORNADA IN (SELECT ID_JORNADA FROM JORNADAS WHERE ID_TEMPORADA = (SELECT MAX(ID_TEMPORADA) FROM TEMPORADAS) AND FECHA < SYSDATE)
    AND
    P.TIPO_PARTIDO = 'FR'
GROUP BY
    E.ID_EQUIPO, E.NOMBRE
ORDER BY VICTORIAS DESC, DERROTAS, DIFERENCIA_GOLES DESC;