-------------------

-- **** JUGADORES 1K FC ***************** 

INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('GÜNTER','MILOS','09504206P','DC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('ROMAN','GALLARDO','38836192W','DF','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('SORROCHE','PEREZ','84333845K','DC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('MARINO','AZUL','73642257Y','DC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('LEDO','PAREDES','67382497H','DF','WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('SAURAS','SAURON','44468312C','DF','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('BRUNO','PAREJO','26551235N','DF','WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('PLUVINS','MACIAS','70312829N','MC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('RIVERO','LAGO','83490845V','MC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('LAUTARO','ONAINDIA','82453718Y','DC','HABITUAL');

-- **** JUGADORES ANIQUILADORES FC ***************** 

INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('ROGER','ALBERTO','05137433S','MC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('DANIEL','PADORU','21351952V','P','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('GALVANY','FIORE','49119827S','MC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('ANDRES','DE RIVIA','99105035J','DF','WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('XAVIER','MORALES','37183679Q','P','WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('BERNAT','ARNAL','66310778F','MC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('TRILLUS','SEQUIAM','84836063B','DC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('JORQUERA','MANZANO','56792531B','DF','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('GILLES','VINICIUS','42874108S','MC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('JADIR','ASAD','08982946C','DF','HABITUAL');

-- **** JUGADORES EL BARRIO ***************** 

INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('KEVIN','BLANCO','16081657B','DF','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('URIOL','PEDRERA','74327517G','DF','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('JOSE','JUAN','83040852L','MC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('JACOBO','MODRIC','35902391N','DC','WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('PABLO','PEDROLO','23969800M','P','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('BEGUER','GARCIA','39923668S','DC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('MASE','MASA','95757976Y','DF','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('UBON','GUTIERREZ','71874495R','MC','HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('PAU ZZ','SOCRATES','12787645J','DF','WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('BARANERA','BALTO','31463820G','MC','HABITUAL');

-- JIJANTES FC ----------------------------------------------------

INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('ALSINA', 'GUEVARA', '54132048F', 'MC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('POL', 'TORRES', '31677496X', 'P', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('JAY', 'DOE', '67148845T', 'DF', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('QUERO', 'QUASO', '90349711F', 'MC', 'WILDCARD');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('ARNAU', 'MOIS VEUS', '78381432P', 'DF', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('IVAN', 'RAMIREZ', '07407319P', 'DC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('MACA', 'QUINA', '91085276D', 'MC', 'WILDCARD');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('NOEL', 'RAMIREZ', '96080629S', 'DF', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('DORADO', 'NOES', '78528399M', 'DC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('MARIO', 'CASAS', '29606923N', 'P', 'HABITUAL');

-- KUNISPORTS -----------------------------------------------------

INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('CORO', 'GARCIA', '18708542C', 'MC', 'WILDCARD');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('TORRENTOBO', 'PEREZ', '45173267W', 'MC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('VICTOR', 'HERNANDEZ', '22773087M', 'DC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('GUERRERO', 'ALVAREZ', '13519070S', 'P', 'WILDCARD');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('JOAN', 'INES', '19036319R', 'MC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('RODE', 'FERNANDEZ', '96447467A', 'P', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('RUGGERI', 'RIVAS', '57210990P', 'DF', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('NACHO', 'JIMENEZ', '42624614W', 'DF', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('HIDALGO', 'HIERRO', '18978547M', 'DC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('LLUC', 'JOVIC', '70502440B', 'DC', 'HABITUAL');

-- LOS TRONCOS ----------------------------------------------------

INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('CARLOS', 'PLANAS', '32942663Q', 'DC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('EDGAR', 'ALVARO', '32942664Q', 'DC', 'WILDCARD');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('PEDRO', 'LECHUGA', '02578857M', 'P', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('DARIO', 'SORIANO', '02460131M', 'DF', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('SERGIO', 'SALVAGE', '31125929Y', 'MC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('NOEL', 'LUIS', '66362824G', 'MC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('XAVI', 'MOLAS', '70965292B', 'MC', 'WILDCARD');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('RAUL', 'MARTINEZ', '29905438X', 'DC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('DORKIS', 'ANGULO', '72963063W', 'DC', 'HABITUAL');
INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('IKER', 'NUEVO', '93545980N', 'MC', 'HABITUAL');

--------------------------------------------------------------

--ULTIMATE MOSTOLES
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('ARCHE', 'MORALES', '69805483T', 'MC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('LU', 'PEDRALES', '77448440B', 'P', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('GUTI', 'AGÜERO', '04042461G', 'DF', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('ALEIX', 'FERNANDEZ', '89020602E', 'MC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('LLUR', 'CROISSANT', '69969749T', 'DC', 'WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('IKER', 'MORTADELO', '24266868M', 'DF', 'WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('IAN', 'MARIN', '50335910L', 'DF', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('ZEA', 'BARROCA', '21341733X', 'DC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('NACHO', 'VIDAL', '88291442P', 'P', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('LUCCA', 'HARRELSON', '62575617T', 'MC', 'HABITUAL');


--PIO FC
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('LOPO', 'BURGOS', '28930681Q', 'MC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('JORGE', 'FERNANDEZ', '74528749D', 'P', 'WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('CARLITOS', 'PEQUE', '44544198Y', 'DF', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('PAU', 'FER', '45664758Y', 'MC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('IGOR', 'CABELLO', '35564086Z', 'DC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('BENITO', 'JUAREZ', '14568442N', 'MC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('TURNER', 'PEREZ', '65118143Z', 'DF', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('ADRI', 'CACERES', '09071195H', 'DC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('COKITA', 'RIVAS', '32946176X', 'MC', 'WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('ALVARO', 'ROPERO', '31869817M', 'MC', 'HABITUAL');

--SAIYANS FC
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('BRIONES', 'CANOVAS', '46094484T', 'P', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('GIO', 'FERINU', '44212850L', 'DC', 'WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('CAMPU', 'ARNOLD', '74622655Y', 'DF', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('TEMO', 'STUART', '01655195T', 'MC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('CARLOS', 'VALLE', '56674039S', 'DC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('VILLA', 'TORRES', '39114483Q', 'DF', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('FELIU', 'JIMENEZ', '83688929W', 'MC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('DAVID', 'ALBA', '45408613N', 'DC', 'WILDCARD');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('RUBEN', 'CARBO', '98408132X', 'MC', 'HABITUAL');
INSERT INTO JUGADORES (NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('UNAI', 'FAJARDO', '15865215E', 'P', 'HABITUAL');

--------------------
-- PORCINOS FC
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('ESPINOSA','PINCHA','09172814T','MC','WILDCARD');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('JUANLU','SEGOVIA','22044212T','P','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('GERARD','CICHERO','66938620H','MC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('DAVID','LLANOS','20579018K','DF','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('TOTI','JAN','03648205Z','DF','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('CARLITOS','GONZALEZ','47268912W','MC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('KILLIAN','MBAPPE','77055639G','DC','WILDCARD');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('JULIAN','BLANCO','39777155N','MC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('URI ','PONS','01232189X','DC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('LAO','FRENTELLADOS','87076994Y','DF','WILDCARD');

-- RAYO DE BARCELONA 

INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('POLOTELI ','PEREZ','55467668V','DC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('PELAZ ','PIERROT','25085466X','MC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('CANET ','CIFUENTES','60386827M','P','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('GUILLEM ','ZZ','32712547S','DC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('MARIO ','REYES','58181044Z','DF','WILDCARD');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('FRANKY','PUERTAS','72807614X','MC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('DANI','PAJARES','94897031C','MC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('ALEJANDRO ','MACIAS','22070166X','DF','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('BILBOUM ','MARTINEZ','81032583H','DC','WILDCARD');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('JONATHAN','CABALLERO','53727541R','MC','HABITUAL');

-- XBUYER TEAM

INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('CRISTIAN','CASTRO','17100019W','DC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('CAPI ','BARA','03270935J','P','WILDCARD');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('POCH ','GARCIA','52127678H','DC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('IÑAKI ','LOPEZ','54061353Z','MC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('DANI ','TORRES','63907810X','DC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('GRANERO','JIMENEZ','20415329T','DC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('GORAN','PETROVIC','27806432F','MC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('BAÑULS ','MARTINEZ','49326138Q','DF','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('FRANC ','SANCHEZ','09504207P','MC','HABITUAL');
INSERT INTO JUGADORES(NOMBRE,APELLIDO,DNI,POSICION,TIPO_JUGADOR) values ('BENJAMIN','SIERRA','38836193W','DC','WILDCARD');
