-- ******* TEMPORADA *****************************************

INSERT INTO TEMPORADAS (FECHA_INICIO, FECHA_FIN, ESTADO, PERIODO) 
VALUES (TO_DATE('12/11/2022', 'DD/MM/YYYY'),TO_DATE('26/03/2023', 'DD/MM/YYYY'),
'CERRADO','INV');

-- ******* JORNADAS *****************************************

INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,1,TO_DATE('01/01/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,2,TO_DATE('08/01/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,3,TO_DATE('15/01/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,4,TO_DATE('22/01/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,5,TO_DATE('05/02/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,6,TO_DATE('12/02/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,7,TO_DATE('19/02/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,8,TO_DATE('26/02/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,9,TO_DATE('05/03/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,10,TO_DATE('12/03/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,11,TO_DATE('19/03/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,12,TO_DATE('24/03/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,13,TO_DATE('26/03/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,14,TO_DATE('26/03/2023', 'DD/MM/YYYY'));

-- ******* PARTIDOS *****************************************

-- JORNADA 1

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 1, 1);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 1, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 1, 3);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 1, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 1, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 1, 9);

-- JORNADA 2

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 2, 11);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 2, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 2, 1);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 2, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 2, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 2, 9);

-- JORNADA 3

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 3, 1);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 3, 12);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 3, 9);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 3, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 3, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 3, 2);

-- JORNADA 4

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 4, 12);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 4, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 4, 3);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 4, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 4, 2);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 4, 7);

-- JORNADA 5

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 5, 12);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 5, 9);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 5, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 5, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 5, 11);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 5, 2); -- TRONCOS / ANIQUILADORES 5-6 

-- JORNADA 6

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 6, 8);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 6, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 6, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 6, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 6, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 6, 9); -- 1K FC / SAIYANS (3)2-2(4) 

-- JORNADA 7

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 7, 11);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 7, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 7, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 7, 8);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 7, 9);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 7, 3); -- EL BARRIO / KUNI 6-2

-- JORNADA 8

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 8, 2);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 8, 3);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 8, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 8, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 8, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 8, 8);

-- JORNADA 9

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 9, 9);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 9, 1);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 9, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 9, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 9, 3);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 9, 12);

-- JORNADA 10

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 10, 12);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 10, 4);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 10, 1);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 10, 2);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 10, 8);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 10, 6);

-- JORNADA 11

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 11, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 11, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 11, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 11, 12);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 11, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 11, 2);

-- JORNADA 12 (PLAYOFF)

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '20:00' , 12, 9);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '21:00' , 12, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '19:00' , 12, 2);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '18:00' , 12, 3);

-- JORNADA 13 (SEMIFINALES)

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '20:00' , 13, 2);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '21:00' , 13, 3);

-- JORNADA 14 (FINAL)

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '21:00' , 14, 3);

-- ******* PARTIDOS LOCALES/VISITANTES *****************************************

-- JORNADA 1

INSERT INTO PARTIDOS_LOCALES VALUES (11,1,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,1,4);

INSERT INTO PARTIDOS_LOCALES VALUES (5,2,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (4,2,1);

INSERT INTO PARTIDOS_LOCALES VALUES (3,3,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (8,3,0);

INSERT INTO PARTIDOS_LOCALES VALUES (6,4,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,4,3);

INSERT INTO PARTIDOS_LOCALES VALUES (2,5,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,5,5);

INSERT INTO PARTIDOS_LOCALES VALUES (9,6,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (10,6,2);

-- JORNADA 2

INSERT INTO PARTIDOS_LOCALES VALUES (4,7,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (11,7,5);

INSERT INTO PARTIDOS_LOCALES VALUES (7,8,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,8,2);

INSERT INTO PARTIDOS_LOCALES VALUES (1,9,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,9,2);

INSERT INTO PARTIDOS_LOCALES VALUES (10,10,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,10,3);

INSERT INTO PARTIDOS_LOCALES VALUES (12,11,0);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,11,1);

INSERT INTO PARTIDOS_LOCALES VALUES (8,12,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,12,4);

-- JORNADA 3

INSERT INTO PARTIDOS_LOCALES VALUES (4,13,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,13,5);

INSERT INTO PARTIDOS_LOCALES VALUES (11,14,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,14,5);

INSERT INTO PARTIDOS_LOCALES VALUES (9,15,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,15,1);

INSERT INTO PARTIDOS_LOCALES VALUES (5,16,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (10,16,5);

INSERT INTO PARTIDOS_LOCALES VALUES (6,17,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (8,17,2);

INSERT INTO PARTIDOS_LOCALES VALUES (3,18,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,18,4);

-- JORNADA 4

INSERT INTO PARTIDOS_LOCALES VALUES (12,19,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (4,19,2);

INSERT INTO PARTIDOS_LOCALES VALUES (8,20,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,21,4);

INSERT INTO PARTIDOS_LOCALES VALUES (1,22,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,22,5);

INSERT INTO PARTIDOS_LOCALES VALUES (10,23,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (11,23,1);

INSERT INTO PARTIDOS_LOCALES VALUES (2,24,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,24,3);

INSERT INTO PARTIDOS_LOCALES VALUES (7,25,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,25,1);

-- JORNADA 5

INSERT INTO PARTIDOS_LOCALES VALUES (12,26,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,26,2);

INSERT INTO PARTIDOS_LOCALES VALUES (9,27,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,27,0);

INSERT INTO PARTIDOS_LOCALES VALUES (5,28,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,28,1);

INSERT INTO PARTIDOS_LOCALES VALUES (4,29,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (10,29,4);

INSERT INTO PARTIDOS_LOCALES VALUES (11,30,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (8,30,4);

INSERT INTO PARTIDOS_LOCALES VALUES (6,31,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,31,6);

-- JORNADA 6

INSERT INTO PARTIDOS_LOCALES VALUES (8,32,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (4,32,0);

INSERT INTO PARTIDOS_LOCALES VALUES (3,33,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,33,7);

INSERT INTO PARTIDOS_LOCALES VALUES (7,34,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (11,34,2);

INSERT INTO PARTIDOS_LOCALES VALUES (2,35,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,35,3);

INSERT INTO PARTIDOS_LOCALES VALUES (10,36,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,36,3);

INSERT INTO PARTIDOS_LOCALES VALUES (1,37,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,37,6);

-- JORNADA 7

INSERT INTO PARTIDOS_LOCALES VALUES (11,38,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,38,2);

INSERT INTO PARTIDOS_LOCALES VALUES (10,39,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,39,2);

INSERT INTO PARTIDOS_LOCALES VALUES (4,40,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,40,4);

INSERT INTO PARTIDOS_LOCALES VALUES (12,41,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (8,41,5);

INSERT INTO PARTIDOS_LOCALES VALUES (6,42,0);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,42,1);

INSERT INTO PARTIDOS_LOCALES VALUES (3,43,6);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,43,2);

-- JORNADA 8

INSERT INTO PARTIDOS_LOCALES VALUES (2,44,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (4,44,2);

INSERT INTO PARTIDOS_LOCALES VALUES (3,45,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (11,45,2);

INSERT INTO PARTIDOS_LOCALES VALUES (7,46,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,46,1);

INSERT INTO PARTIDOS_LOCALES VALUES (9,47,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,47,3);

INSERT INTO PARTIDOS_LOCALES VALUES (1,48,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,48,5);

INSERT INTO PARTIDOS_LOCALES VALUES (8,49,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (10,49,1);

-- JORNADA 9

INSERT INTO PARTIDOS_LOCALES VALUES (11,50,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,50,3);

INSERT INTO PARTIDOS_LOCALES VALUES (8,51,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,51,4);

INSERT INTO PARTIDOS_LOCALES VALUES (10,52,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,52,5);

INSERT INTO PARTIDOS_LOCALES VALUES (5,53,0);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,53,4);

INSERT INTO PARTIDOS_LOCALES VALUES (4,54,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,54,3);

INSERT INTO PARTIDOS_LOCALES VALUES (12,55,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,55,0);

-- JORNADA 10

INSERT INTO PARTIDOS_LOCALES VALUES (3,56,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,56,2);

INSERT INTO PARTIDOS_LOCALES VALUES (9,57,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (4,57,5);

INSERT INTO PARTIDOS_LOCALES VALUES (5,58,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,58,2);

INSERT INTO PARTIDOS_LOCALES VALUES (2,59,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (10,59,3);

INSERT INTO PARTIDOS_LOCALES VALUES (7,60,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (8,60,3);

INSERT INTO PARTIDOS_LOCALES VALUES (6,61,6);
INSERT INTO PARTIDOS_VISITANTES VALUES (11,61,3);

-- JORNADA 11

INSERT INTO PARTIDOS_LOCALES VALUES (4,62,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,62,5);

INSERT INTO PARTIDOS_LOCALES VALUES (1,63,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,63,3);

INSERT INTO PARTIDOS_LOCALES VALUES (10,64,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,64,3);

INSERT INTO PARTIDOS_LOCALES VALUES (12,65,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,65,1);

INSERT INTO PARTIDOS_LOCALES VALUES (11,66,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,66,4);

INSERT INTO PARTIDOS_LOCALES VALUES (8,67,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,67,5);

-- JORNADA 12 (PLAYOFFS)

INSERT INTO PARTIDOS_LOCALES VALUES (9,68,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,68,2);

INSERT INTO PARTIDOS_LOCALES VALUES (6,69,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,69,3);

INSERT INTO PARTIDOS_LOCALES VALUES (10,70,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,70,5);

INSERT INTO PARTIDOS_LOCALES VALUES (7,71,0);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,71,3);

-- JORNADA 13 (SEMIFINAL)

INSERT INTO PARTIDOS_LOCALES VALUES (2,72,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,72,4);

INSERT INTO PARTIDOS_LOCALES VALUES (3,73,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,73,3);

-- JORNADA 14 (FINAL)

INSERT INTO PARTIDOS_LOCALES VALUES (3,74,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,74,0);





