-- ******* TEMPORADA *****************************************

INSERT INTO TEMPORADAS (FECHA_INICIO, FECHA_FIN, ESTADO, PERIODO) 
VALUES (TO_DATE('12/11/2022', 'DD/MM/YYYY'),TO_DATE('26/03/2023', 'DD/MM/YYYY'),
'CERRADO','INV');

-- ******* JORNADAS *****************************************

INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,1,TO_DATE('01/01/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,2,TO_DATE('08/01/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,3,TO_DATE('15/01/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,4,TO_DATE('22/01/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,5,TO_DATE('05/02/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,6,TO_DATE('12/02/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,7,TO_DATE('19/02/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,8,TO_DATE('26/02/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,9,TO_DATE('05/03/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,10,TO_DATE('12/03/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,11,TO_DATE('19/03/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,12,TO_DATE('24/03/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,13,TO_DATE('26/03/2023', 'DD/MM/YYYY'));
INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,14,TO_DATE('26/03/2023', 'DD/MM/YYYY'));

-- ******* PARTIDOS *****************************************

-- JORNADA 1

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 1, 1);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 1, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 1, 3);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 1, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 1, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 1, 9);

-- JORNADA 2

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 2, 11);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 2, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 2, 1);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 2, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 2, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 2, 9);

-- JORNADA 3

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 3, 1);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 3, 12);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 3, 9);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 3, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 3, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 3, 2);

-- JORNADA 4

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 4, 12);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 4, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 4, 3);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 4, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 4, 2);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 4, 7);

-- JORNADA 5

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 5, 12);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 5, 9);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 5, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 5, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 5, 11);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 5, 2); -- TRONCOS / ANIQUILADORES 5-6 

-- JORNADA 6

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 6, 8);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 6, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 6, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 6, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 6, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 6, 9); -- 1K FC / SAIYANS (3)2-2(4) 

-- JORNADA 7

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 7, 11);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 7, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 7, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 7, 8);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 7, 9);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 7, 3); -- EL BARRIO / KUNI 6-2

-- JORNADA 8

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 8, 2);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 8, 3);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 8, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 8, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 8, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 8, 8);

-- JORNADA 9

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 9, 9);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 9, 1);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 9, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 9, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 9, 3);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 9, 12);

-- JORNADA 10

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 10, 12);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 10, 4);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 10, 1);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 10, 2);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 10, 8);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 10, 6);

-- JORNADA 11

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '20:00' , 11, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '21:00' , 11, 7);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '19:00' , 11, 10);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '18:00' , 11, 12);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '22:00' , 11, 5);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('FR', '23:00' , 11, 2);

-- JORNADA 12 (PLAYOFF)

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '20:00' , 12, 9);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '21:00' , 12, 6);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '19:00' , 12, 2);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '18:00' , 12, 3);

-- JORNADA 13 (SEMIFINALES)

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '20:00' , 13, 2);
INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '21:00' , 13, 3);

-- JORNADA 14 (FINAL)

INSERT INTO PARTIDOS (TIPO_PARTIDO, HORA, ID_JORNADA, ID_EQUIPO_GANADOR) VALUES ('PO', '21:00' , 14, 3);

-- ******* PARTIDOS LOCALES/VISITANTES *****************************************

-- JORNADA 1

INSERT INTO PARTIDOS_LOCALES VALUES (11,1,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,1,4);

INSERT INTO PARTIDOS_LOCALES VALUES (5,2,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (4,2,1);

INSERT INTO PARTIDOS_LOCALES VALUES (3,3,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (8,3,0);

INSERT INTO PARTIDOS_LOCALES VALUES (6,4,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,4,3);

INSERT INTO PARTIDOS_LOCALES VALUES (2,5,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,5,5);

INSERT INTO PARTIDOS_LOCALES VALUES (9,6,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (10,6,2);

-- JORNADA 2

INSERT INTO PARTIDOS_LOCALES VALUES (4,7,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (11,7,5);

INSERT INTO PARTIDOS_LOCALES VALUES (7,8,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,8,2);

INSERT INTO PARTIDOS_LOCALES VALUES (1,9,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,9,2);

INSERT INTO PARTIDOS_LOCALES VALUES (10,10,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,10,3);

INSERT INTO PARTIDOS_LOCALES VALUES (12,11,0);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,11,1);

INSERT INTO PARTIDOS_LOCALES VALUES (8,12,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,12,4);

-- JORNADA 3

INSERT INTO PARTIDOS_LOCALES VALUES (4,13,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,13,5);

INSERT INTO PARTIDOS_LOCALES VALUES (11,14,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,14,5);

INSERT INTO PARTIDOS_LOCALES VALUES (9,15,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,15,1);

INSERT INTO PARTIDOS_LOCALES VALUES (5,16,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (10,16,5);

INSERT INTO PARTIDOS_LOCALES VALUES (6,17,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (8,17,2);

INSERT INTO PARTIDOS_LOCALES VALUES (3,18,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,18,4);

-- JORNADA 4

INSERT INTO PARTIDOS_LOCALES VALUES (12,19,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (4,19,2);

INSERT INTO PARTIDOS_LOCALES VALUES (8,20,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,20,4);

INSERT INTO PARTIDOS_LOCALES VALUES (1,21,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,21,5);

INSERT INTO PARTIDOS_LOCALES VALUES (10,22,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (11,22,1);

INSERT INTO PARTIDOS_LOCALES VALUES (2,23,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,23,3);

INSERT INTO PARTIDOS_LOCALES VALUES (7,24,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,24,1);

-- JORNADA 5

INSERT INTO PARTIDOS_LOCALES VALUES (12,25,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,25,2);

INSERT INTO PARTIDOS_LOCALES VALUES (9,26,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,26,0);

INSERT INTO PARTIDOS_LOCALES VALUES (5,27,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,27,1);

INSERT INTO PARTIDOS_LOCALES VALUES (4,28,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (10,28,4);

INSERT INTO PARTIDOS_LOCALES VALUES (11,29,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (8,29,4);

INSERT INTO PARTIDOS_LOCALES VALUES (6,30,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,30,6);

-- JORNADA 6

INSERT INTO PARTIDOS_LOCALES VALUES (8,31,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (4,31,0);

INSERT INTO PARTIDOS_LOCALES VALUES (3,32,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,32,7);

INSERT INTO PARTIDOS_LOCALES VALUES (7,33,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (11,33,2);

INSERT INTO PARTIDOS_LOCALES VALUES (2,34,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,34,3);

INSERT INTO PARTIDOS_LOCALES VALUES (10,35,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,35,3);

INSERT INTO PARTIDOS_LOCALES VALUES (1,36,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,36,6);

-- JORNADA 7

INSERT INTO PARTIDOS_LOCALES VALUES (11,37,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,37,2);

INSERT INTO PARTIDOS_LOCALES VALUES (10,38,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,38,2);

INSERT INTO PARTIDOS_LOCALES VALUES (4,39,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,39,4);

INSERT INTO PARTIDOS_LOCALES VALUES (12,40,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (8,40,5);

INSERT INTO PARTIDOS_LOCALES VALUES (6,41,0);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,41,1);

INSERT INTO PARTIDOS_LOCALES VALUES (3,42,6);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,42,2);

-- JORNADA 8

INSERT INTO PARTIDOS_LOCALES VALUES (2,43,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (4,43,2);

INSERT INTO PARTIDOS_LOCALES VALUES (3,44,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (11,44,2);

INSERT INTO PARTIDOS_LOCALES VALUES (7,45,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,45,1);

INSERT INTO PARTIDOS_LOCALES VALUES (9,46,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,46,3);

INSERT INTO PARTIDOS_LOCALES VALUES (1,47,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,47,5);

INSERT INTO PARTIDOS_LOCALES VALUES (8,48,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (10,48,1);

-- JORNADA 9

INSERT INTO PARTIDOS_LOCALES VALUES (11,49,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,49,3);

INSERT INTO PARTIDOS_LOCALES VALUES (8,50,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,50,4);

INSERT INTO PARTIDOS_LOCALES VALUES (10,51,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,51,5);

INSERT INTO PARTIDOS_LOCALES VALUES (5,52,0);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,52,4);

INSERT INTO PARTIDOS_LOCALES VALUES (4,53,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,53,3);

INSERT INTO PARTIDOS_LOCALES VALUES (12,54,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,54,0);

-- JORNADA 10

INSERT INTO PARTIDOS_LOCALES VALUES (3,55,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,55,2);

INSERT INTO PARTIDOS_LOCALES VALUES (9,56,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (4,56,5);

INSERT INTO PARTIDOS_LOCALES VALUES (5,57,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (1,57,2);

INSERT INTO PARTIDOS_LOCALES VALUES (2,58,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (10,58,3);

INSERT INTO PARTIDOS_LOCALES VALUES (7,59,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (8,59,3);

INSERT INTO PARTIDOS_LOCALES VALUES (6,60,6);
INSERT INTO PARTIDOS_VISITANTES VALUES (11,60,3);

-- JORNADA 11

INSERT INTO PARTIDOS_LOCALES VALUES (4,61,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,61,5);

INSERT INTO PARTIDOS_LOCALES VALUES (1,62,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (7,62,3);

INSERT INTO PARTIDOS_LOCALES VALUES (10,63,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,63,3);

INSERT INTO PARTIDOS_LOCALES VALUES (12,64,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,64,1);

INSERT INTO PARTIDOS_LOCALES VALUES (11,65,1);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,65,4);

INSERT INTO PARTIDOS_LOCALES VALUES (8,66,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,66,5);

-- JORNADA 12 (PLAYOFFS)

INSERT INTO PARTIDOS_LOCALES VALUES (9,67,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (5,67,2);

INSERT INTO PARTIDOS_LOCALES VALUES (6,68,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (12,68,3);

INSERT INTO PARTIDOS_LOCALES VALUES (10,69,2);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,69,5);

INSERT INTO PARTIDOS_LOCALES VALUES (7,70,0);
INSERT INTO PARTIDOS_VISITANTES VALUES (3,70,3);

-- JORNADA 13 (SEMIFINAL)

INSERT INTO PARTIDOS_LOCALES VALUES (2,71,5);
INSERT INTO PARTIDOS_VISITANTES VALUES (6,71,4);

INSERT INTO PARTIDOS_LOCALES VALUES (3,72,4);
INSERT INTO PARTIDOS_VISITANTES VALUES (9,72,3);

-- JORNADA 14 (FINAL)

INSERT INTO PARTIDOS_LOCALES VALUES (3,73,3);
INSERT INTO PARTIDOS_VISITANTES VALUES (2,73,0);
