CREATE OR REPLACE TRIGGER PRES_KINGS_LEAGUE
FOR INSERT OR UPDATE OF SUELDO, ID_JUGADOR
ON EQUIPOS_JUGADORES 
COMPOUND TRIGGER
    NewSueldo EQUIPOS_JUGADORES.SUELDO%type := null;
    NewIdEquipo EQUIPOS_JUGADORES.ID_EQUIPO%type :=null;
    BEFORE EACH ROW IS
    BEGIN
       NewSueldo := :new.sueldo;
       NewIdEquipo := :new.id_equipo;
    END BEFORE EACH ROW;
    AFTER STATEMENT IS
    N_SUELDO NUMBER;
    N_PRESUPUESTO NUMBER;
    BEGIN
        SELECT sum(sueldo) into N_SUELDO
        FROM EQUIPOS_JUGADORES 
        WHERE ID_EQUIPO = NewIdEquipo;
        SELECT PRESUPUESTO into N_PRESUPUESTO
        FROM EQUIPOS
        WHERE ID_EQUIPO = NewIdEquipo;
        IF N_SUELDO > N_PRESUPUESTO
            THEN
            RAISE_APPLICATION_ERROR(-20001,'EL SUELDO TOTAL ES MAYOR QUE EL PRESUPUESTO DEL EQUIPO');
        END IF;
    END AFTER STATEMENT;
END PRES_KINGS_LEAGUE;

/* 

INSERT INTO EQUIPOS_JUGADORES 
VALUES (3,1,201000000,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000)
Informe de error -
ORA-20001: EL SUELDO TOTAL ES MAYOR QUE EL PRESUPUESTO DEL EQUIPO
ORA-06512: en "EQDAW04.PRES_KINGS_LEAGUE", línea 21
ORA-04088: error durante la ejecución del disparador 'EQDAW04.PRES_KINGS_LEAGUE'

*/