CREATE OR REPLACE TRIGGER TRG_GENERAR_CALENDARIO
BEFORE INSERT OR UPDATE ON JORNADAS
FOR EACH ROW
DECLARE
    V_NUM_JUGADORES NUMBER;
    V_NUM_EQUIPOS NUMBER;
    verificar_equipos BOOLEAN;
    no_suficientes_equipos EXCEPTION;
    menos_de_8_jugadores EXCEPTION;
BEGIN
    verificar_equipos := validar_minimo_equipos();
    IF verificar_equipos = FALSE THEN
        RAISE no_suficientes_equipos;
    END IF;
    FOR i IN 1..12 LOOP
        SELECT COUNT(*) INTO V_NUM_JUGADORES 
        FROM EQUIPOS_JUGADORES 
        WHERE ID_JUGADOR IN (SELECT ID_JUGADOR FROM JUGADORES WHERE UPPER(TIPO_JUGADOR) = 'HABITUAL')
        GROUP BY ID_EQUIPO HAVING ID_EQUIPO = i;
        IF V_NUM_JUGADORES < 8 THEN
            RAISE menos_de_8_jugadores;
        END IF;
    END LOOP;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO ESTAN TODOS LOS EQUIPOS');
    WHEN no_suficientes_equipos THEN
        DBMS_OUTPUT.PUT_LINE('No hay suficientes equipos para generar el calendario');
    WHEN menos_de_8_jugadores THEN
        DBMS_OUTPUT.PUT_LINE('No todos los equipos tienen 8 jugadores habituales');
END;


/* 

ERROR Nº1
--------------

INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,1,TO_DATE('01/01/2023', 'DD/MM/YYYY'))
Informe de error -
ORA-20004: NO ESTAN TODOS LOS EQUIPOS
ORA-06512: en "EQDAW04.TRG_GENERAR_CALENDARIO", línea 15
ORA-04088: error durante la ejecución del disparador 'EQDAW04.TRG_GENERAR_CALENDARIO'

ERROR Nº2
--------------

INSERT INTO JORNADAS (ID_TEMPORADA, NUM_JORNADA, FECHA) VALUES (1,1,TO_DATE('01/01/2023', 'DD/MM/YYYY'))
Informe de error -
ORA-20003: EL EQUIPO CON EL ID: 1 TIENE MENOS DE 8 JUGADORES, NO SE PUEDE GENERAR LA JORNADA
ORA-06512: en "EQDAW04.TRG_GENERAR_CALENDARIO", línea 10
ORA-04088: error durante la ejecución del disparador 'EQDAW04.TRG_GENERAR_CALENDARIO'

*/


CREATE OR REPLACE TRIGGER VERIFICIAR_JUGADORES
FOR INSERT OR UPDATE ON EQUIPOS_JUGADORES
COMPOUND TRIGGER

  -- Declarar variables globales para el trigger
  CANT_WILDCARDS NUMBER(2);
  CANT_HABITUALES NUMBER;
  NEW_TIPO_JUGADOR VARCHAR(20);

BEFORE EACH ROW IS
BEGIN

  --SELECT DE LA CANTIDAD DE JUGADORES DE TIPO WILDCARD EN EL EQUIPO QUE SE QUIERE INSERTAR, METEMOS EL RESULTADO EN LA VARIABLE CANT_WILDCARDS.
  SELECT COUNT(*) INTO CANT_WILDCARDS FROM EQUIPOS_JUGADORES
    WHERE ID_EQUIPO = :NEW.ID_EQUIPO AND ID_JUGADOR IN (SELECT ID_JUGADOR FROM JUGADORES WHERE TIPO_JUGADOR = 'WILDCARD');
    
  SELECT COUNT(*) INTO CANT_HABITUALES FROM EQUIPOS_JUGADORES
    WHERE ID_EQUIPO = :NEW.ID_EQUIPO AND ID_JUGADOR IN (SELECT ID_JUGADOR FROM JUGADORES WHERE TIPO_JUGADOR = 'HABITUAL');
    
  SELECT TIPO_JUGADOR INTO NEW_TIPO_JUGADOR FROM JUGADORES WHERE ID_JUGADOR = :NEW.ID_JUGADOR; 
  --SI LA VARIABLE ES =2 Y EL TIPO DE JUGADOR ES WILDCARD SACAMOS UN ERROR POR PANTALLA.
END BEFORE EACH ROW;
AFTER EACH ROW IS
BEGIN
    IF NEW_TIPO_JUGADOR = 'WILDCARD' THEN
        IF CANT_WILDCARDS = 2 THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PUEDEN TENER MAS DE 2 JUGADORES DE TIPO WILDCARD');
        END IF;
    ELSE
        IF CANT_HABITUALES = 8 THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PUEDEN TENER MAS DE 8 JUGADORES DE TIPO HABITUAL');
        END IF;
    END IF;
END AFTER EACH ROW;  
END VERIFICIAR_JUGADORES;


/* INSERT PARA LAS PRUEBAS

INSERT INTO EQUIPOS_JUGADORES VALUES (1,1,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000);
INSERT INTO EQUIPOS_JUGADORES VALUES (1,2,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000);
INSERT INTO EQUIPOS_JUGADORES VALUES (1,3,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000);
INSERT INTO EQUIPOS_JUGADORES VALUES (1,4,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000);
INSERT INTO EQUIPOS_JUGADORES VALUES (1,6,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000);
INSERT INTO EQUIPOS_JUGADORES VALUES (1,8,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000);
INSERT INTO EQUIPOS_JUGADORES VALUES (1,9,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000);
INSERT INTO EQUIPOS_JUGADORES VALUES (1,10,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000);

ERROR Nº1 [MÁS DE 8 HABITUALES]
---------------------------------------

INSERT INTO EQUIPOS_JUGADORES VALUES (1,14,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000)
Informe de error -
ORA-20001: NO SE PUEDEN TENER MAS DE 2 JUGADORES DE TIPO WILDCARD
ORA-06512: en "EQDAW04.TRG_VERIFICAR_WILDCARD_1", línea 25
ORA-04088: error durante la ejecución del disparador 'EQDAW04.TRG_VERIFICAR_WILDCARD_1'


INSERT INTO EQUIPOS_JUGADORES VALUES (1,5,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000);
INSERT INTO EQUIPOS_JUGADORES VALUES (1,7,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000);


ERROR Nº2 [MÁS DE 2 WILDCARDS]
--------------------------------------

INSERT INTO EQUIPOS_JUGADORES VALUES (1,18,200,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000)
Informe de error -
ORA-20001: NO SE PUEDEN TENER MAS DE 8 JUGADORES DE TIPO HABITUAL
ORA-06512: en "EQDAW04.TRG_VERIFICAR_WILDCARD_1", línea 29
ORA-04088: error durante la ejecución del disparador 'EQDAW04.TRG_VERIFICAR_WILDCARD_1'

*/

CREATE OR REPLACE TRIGGER PRES_KINGS_LEAGUE
FOR INSERT OR UPDATE OF SUELDO, ID_JUGADOR
ON EQUIPOS_JUGADORES 
COMPOUND TRIGGER
    NewSueldo EQUIPOS_JUGADORES.SUELDO%type := null;
    NewIdEquipo EQUIPOS_JUGADORES.ID_EQUIPO%type :=null;
    BEFORE EACH ROW IS
    BEGIN
       NewSueldo := :new.sueldo;
       NewIdEquipo := :new.id_equipo;
    END BEFORE EACH ROW;
    AFTER STATEMENT IS
    N_SUELDO NUMBER;
    N_PRESUPUESTO NUMBER;
    BEGIN
        SELECT sum(sueldo) into N_SUELDO
        FROM EQUIPOS_JUGADORES 
        WHERE ID_EQUIPO = NewIdEquipo;
        SELECT PRESUPUESTO into N_PRESUPUESTO
        FROM EQUIPOS
        WHERE ID_EQUIPO = NewIdEquipo;
        IF N_SUELDO > N_PRESUPUESTO
            THEN
            RAISE_APPLICATION_ERROR(-20001,'EL SUELDO TOTAL ES MAYOR QUE EL PRESUPUESTO DEL EQUIPO');
        END IF;
    END AFTER STATEMENT;
END PRES_KINGS_LEAGUE;

/* 

INSERT INTO EQUIPOS_JUGADORES 
VALUES (3,1,201000000,TO_DATE('17/04/2022', 'DD/MM/YYYY'),TO_DATE('20/04/2022', 'DD/MM/YYYY'), 2000000)
Informe de error -
ORA-20001: EL SUELDO TOTAL ES MAYOR QUE EL PRESUPUESTO DEL EQUIPO
ORA-06512: en "EQDAW04.PRES_KINGS_LEAGUE", línea 21
ORA-04088: error durante la ejecución del disparador 'EQDAW04.PRES_KINGS_LEAGUE'

*/


DROP TRIGGER INSCRIPCIONES_KINGS_LEAGUE;

-- PARA TEMPORADAS --------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER INSCRIPCIONES_KINGS_LEAGUE
FOR UPDATE OF ESTADO ON TEMPORADAS
COMPOUND TRIGGER
    V_ESTADO VARCHAR2(20) := NULL;
    
    BEFORE STATEMENT IS
    BEGIN
        SELECT ESTADO INTO V_ESTADO FROM TEMPORADAS WHERE ID_TEMPORADA = (SELECT MAX(ID_TEMPORADA) FROM TEMPORADAS);
    END BEFORE STATEMENT;
    
    AFTER STATEMENT IS
    BEGIN
        IF UPPER(V_ESTADO) = 'CERRADO'
        THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PUEDE VOLVER A ABRIR LA INSCRIPCION');
        END IF;
    END AFTER STATEMENT;    
END INSCRIPCIONES_KINGS_LEAGUE;

/*

UPDATE TEMPORADAS SET ESTADO = 'CERRADO' WHERE ID_TEMPORADA = 1
Error report -
ORA-20001: NO SE PUEDE INSCRIBIR
ORA-06512: at "SYSTEM.INSCRIPCIONES_KINGS_LEAGUE", line 13
ORA-04088: error during execution of trigger 'SYSTEM.INSCRIPCIONES_KINGS_LEAGUE'

*/

-- PARA EQUIPOS ----------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER INSCR_KINGS_LEAGUE_EQU
BEFORE INSERT OR UPDATE OR DELETE ON EQUIPOS
DECLARE
    V_ESTADO VARCHAR(20);
BEGIN
    SELECT ESTADO INTO V_ESTADO FROM TEMPORADAS WHERE ID_TEMPORADA = 1;
    IF UPPER(V_ESTADO) = 'CERRADO'
    THEN
        RAISE_APPLICATION_ERROR(-20001, 'INSCRIPCION FINALIZADA NO SE PUEDE ACTUALIZAR NI INSERTAR EQUIPOS');
        END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20004,'ERROR (SQL ERROR)');
END INSCR_KINGS_LEAGUE_EQU;

/*

INSERT INTO EQUIPOS(NOMBRE, PRESUPUESTO) VALUES ('PORCINOS FC', 200000000)
Error report -
ORA-20001: INSCRIPCION FINALIZADA NO SE PUEDE ACTUALIZAR NI INSERTAR EQUIPOS
ORA-06512: at "SYSTEM.INSCR_KINGS_LEAGUE_EQU", line 7
ORA-04088: error during execution of trigger 'SYSTEM.INSCRIPCIONES_KINGS_LEAGUE_EQUIPOS'

*/

-- PARA JUGADORES ----------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER INSCR_KINGS_LEAGUE_JUG
BEFORE INSERT OR UPDATE OR DELETE ON JUGADORES
DECLARE
    V_ESTADO VARCHAR(20);
BEGIN
    SELECT ESTADO INTO V_ESTADO FROM TEMPORADAS WHERE ID_TEMPORADA = 1;
    IF UPPER(V_ESTADO) = 'CERRADO'
    THEN
        RAISE_APPLICATION_ERROR(-20001, 'INSCRIPCION FINALIZADA NO SE PUEDE ACTUALIZAR NI INSERTAR JUGADORES');
        END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20004,'ERROR (SQL ERROR)');
END INSCR_KINGS_LEAGUE_JUG;


/*

INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('PAU', 'ZZ', '72825948A', 'DC', 'HABITUAL')
Error report -
ORA-20001: INSCRIPCION FINALIZADA NO SE PUEDE ACTUALIZAR NI INSERTAR JUGADORES
ORA-06512: at "SYSTEM.INSCR_KINGS_LEAGUE_JUG", line 7
ORA-04088: error during execution of trigger 'SYSTEM.INSCRIPCIONES_KINGS_LEAGUE_JUGADORES'

*/


CREATE OR REPLACE FUNCTION VALIDAR_MINIMO_EQUIPOS
  RETURN BOOLEAN
IS
  v_minimo NUMBER := 12;
  v_num_equipos NUMBER;
BEGIN
  Select count(*) into v_num_equipos from equipos;
  IF v_num_equipos < v_minimo THEN
    RETURN FALSE;
  ELSE
    RETURN TRUE;
  END IF;
END;


