
DROP TRIGGER INSCRIPCIONES_KINGS_LEAGUE;

-- PARA TEMPORADAS --------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER INSCRIPCIONES_KINGS_LEAGUE
FOR UPDATE OF ESTADO ON TEMPORADAS
COMPOUND TRIGGER
    V_ESTADO VARCHAR2(20) := NULL;
    
    BEFORE STATEMENT IS
    BEGIN
        SELECT ESTADO INTO V_ESTADO FROM TEMPORADAS WHERE ID_TEMPORADA = 1;
    END BEFORE STATEMENT;
    
    AFTER STATEMENT IS
    BEGIN
        IF UPPER(V_ESTADO) = 'CERRADO'
        THEN
            RAISE_APPLICATION_ERROR(-20001, 'NO SE PUEDE INSCRIBIR');
        END IF;
    END AFTER STATEMENT;    
END INSCRIPCIONES_KINGS_LEAGUE;

/*

UPDATE TEMPORADAS SET ESTADO = 'CERRADO' WHERE ID_TEMPORADA = 1
Error report -
ORA-20001: NO SE PUEDE INSCRIBIR
ORA-06512: at "SYSTEM.INSCRIPCIONES_KINGS_LEAGUE", line 13
ORA-04088: error during execution of trigger 'SYSTEM.INSCRIPCIONES_KINGS_LEAGUE'

*/

-- PARA EQUIPOS ----------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER INSCR_KINGS_LEAGUE_EQU
BEFORE INSERT OR UPDATE ON EQUIPOS
FOR EACH ROW
DECLARE
    V_ESTADO VARCHAR(20);
BEGIN
    SELECT ESTADO INTO V_ESTADO FROM TEMPORADAS WHERE ID_TEMPORADA = 1;
    IF UPPER(V_ESTADO) = 'CERRADO'
    THEN
        RAISE_APPLICATION_ERROR(-20001, 'INSCRIPCION FINALIZADA NO SE PUEDE ACTUALIZAR NI INSERTAR EQUIPOS');
        END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20004,'ERROR (SQL ERROR)');
END INSCR_KINGS_LEAGUE_EQU;

/*

INSERT INTO EQUIPOS(NOMBRE, PRESUPUESTO) VALUES ('PORCINOS FC', 200000000)
Error report -
ORA-20001: INSCRIPCION FINALIZADA NO SE PUEDE ACTUALIZAR NI INSERTAR EQUIPOS
ORA-06512: at "SYSTEM.INSCR_KINGS_LEAGUE_EQU", line 7
ORA-04088: error during execution of trigger 'SYSTEM.INSCRIPCIONES_KINGS_LEAGUE_EQUIPOS'

*/

-- PARA JUGADORES ----------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER INSCR_KINGS_LEAGUE_JUG
BEFORE INSERT OR UPDATE ON JUGADORES
FOR EACH ROW
DECLARE
    V_ESTADO VARCHAR(20);
BEGIN
    SELECT ESTADO INTO V_ESTADO FROM TEMPORADAS WHERE ID_TEMPORADA = 1;
    IF UPPER(V_ESTADO) = 'CERRADO'
    THEN
        RAISE_APPLICATION_ERROR(-20001, 'INSCRIPCION FINALIZADA NO SE PUEDE ACTUALIZAR NI INSERTAR JUGADORES');
        END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20004,'ERROR (SQL ERROR)');
END INSCR_KINGS_LEAGUE_JUG;


/*

INSERT INTO JUGADORES(NOMBRE, APELLIDO, DNI, POSICION, TIPO_JUGADOR) VALUES ('PAU', 'ZZ', '72825948A', 'DC', 'HABITUAL')
Error report -
ORA-20001: INSCRIPCION FINALIZADA NO SE PUEDE ACTUALIZAR NI INSERTAR JUGADORES
ORA-06512: at "SYSTEM.INSCR_KINGS_LEAGUE_JUG", line 7
ORA-04088: error during execution of trigger 'SYSTEM.INSCRIPCIONES_KINGS_LEAGUE_JUGADORES'

*/


